# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

## YAML Template.
---
compas:
  scl:
    schema:
      paths: ## Define all schemas (namespace) path here : (alias: "path")
        - scl: "classpath:schema/SCL.xsd"