<!-- SPDX-FileCopyrightText: 2021 Alliander N.V. -->
<!-- -->
<!-- SPDX-License-Identifier: Apache-2.0 -->
<SCL xmlns="http://www.iec.ch/61850/2003/SCL" xmlns:compas="https://www.lfenergy.org/compas/extension/v1" version="2007"
     revision="B">
    <Private type="compas_scl">
        <compas:SclName>project</compas:SclName>
        <compas:SclFileType>CID</compas:SclFileType>
    </Private>
    <Header id="370e5d89-df3a-4d9b-a651-3dc5cb28bee1" version="1.0.0"/>
</SCL>