# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Build Project

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Create custom Maven Settings.xml
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        output_file: custom_maven_settings.xml
        servers: '[{ "id": "github-packages-compas", "username": "OWNER", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
    - name: Build with Maven
      run: ./mvnw -s custom_maven_settings.xml -B clean verify
