# SPDX-FileCopyrightText: 2022 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: SonarCloud Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  precheck-build:
    name: Pre Check Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Set up JDK 17
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Create custom Maven Settings.xml
        uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d # v22
        with:
          output_file: custom_maven_settings.xml
          servers: '[{ "id": "github-packages-compas", "username": "OWNER", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
      
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw -B -s custom_maven_settings.xml -Psonar clean verify
      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-artifacts
          path: |
            commons/src/
            commons/target/
            rest-commons/src/
            rest-commons/target/
            scl-extension/src/
            scl-extension/target/
            scl2003/src/
            scl2003/target/
            scl2007b/src/
            scl2007b/target/
            scl2007b4/src/
            scl2007b4/target/
            websocket-commons/src/
            websocket-commons/target/
          retention-days: 1
      - name: Save PR number to file
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.pull_request.number }} > PR_NUMBER.txt
      - name: Archive PR number
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt
